### ISSUE TITLE
list student command not displaying students

### ISSUE THREAD

**Issue by Reallyeasy1** [AY2425S1-CS2103T-W08-1/tp#219]
![image](https://github.com/user-attachments/assets/8618116a-3464-45d6-a187-1c1fc0619308)

**Comment by waihongteh** [comment]
For this issue, I think we have discussed before. It is an expected behaviour of the system. Particularly, list method will list all students in the bottom right section. It might seem a bit useless, but if you try to use find command, you will realise that find actually only display the matched students, which is why we need list command to show all students again.
