### ISSUE TITLE
DG - Storage Inaccuracies

### ISSUE THREAD

**Issue by waihongteh** [AY2425S1-CS2103T-W08-1/tp#228]
![image](https://github.com/user-attachments/assets/ffb309c5-b4e9-42f2-8de5-2e074721d791)
The first point says can save address book data and user preference data.
Maybe can include assignments and tutorials as they are in separate json. 
Also Im not very sure if the name addressbook data is appropriate? Are we sticking to addressbook or should we change it to student data?

**Comment by SamsonChew** [comment]
I think the first point is valid and will proceed to amend that. 
For second point on the name of "address book", since the repo now is still under the name of addressbook, for current stage i will close this issue and create another issue on the potential refactor of the name of "address book" that associate with developer guide.
I would follow the principle of developer guide will be written on the current updated repo for better alignment.
