### ISSUE TITLE
[PE-D][Tester B] Tutorial name is not shown

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W08-1/tp#323]
![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/50ba70a4-d0ee-4326-800c-88d601a9c4f9.png)

Tutorial name is not shown, Only the module code is given. This can be confusing as the user might what module is that.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: JunLongling/ped#13

**Comment by Reallyeasy1** [comment]
We wanted the application to be as compact as possible to facilitate the ease of use. Since tutorial name is not unique, we use the tutorial id to uniquely identify which tutorial the student is from. However, if you want to get the tutorial name of the class, simply use listTut to reference what tutorial name the tutorial id has been assigned to.
